apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      serviceAccountName: trading-serviceaccount
      containers:
        - name: trading
          image: wbplayeconomy.azurecr.io/play.trading:1.0.2
          imagePullPolicy: Always
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: wbplayeconomy
            - name: ServiceSettings__Authority
              value: https://wbplayeconomy.eastus.cloudapp.azure.com/identity-svc                          
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5006
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5006
            initialDelaySeconds: 10               

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
  - port: 80
    targetPort: 5006

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.identity/client-id: 9c929f14-bfe0-4999-aa99-3eb4d7066395
  labels:
    azure.workload.identity/use: "true"